name: AVS_iOS_App
options:
  bundleIdPrefix: com.animevietsub
targets:
  AVS_iOS_App:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Core
        type: group
      - path: Core/Extensions
        type: group
      - path: Core/Coordinators
        type: group
      - path: UI
        type: group
      - path: UI/Components
        type: group
      - path: Assets.xcassets
      - path: AppDelegate.swift
    info:
      path: Info.plist
